### ISSUE TITLE
Trying to find Corp-Laptop VM

### ISSUE THREAD

**Issue by ahatamleh** [PacktPublishing/Incident-Response-with-Threat-Intelligence#1]
Virtual machines folder shows no corp-laptop VM files

**Comment by r0bertmart1nez** [comment]
Hi,

You’re right, I’ll upload the Corp-Laptop VM.

Thank you for your feedback.

Regards.

Roberto M.

________________________________
From: ahatamleh ***@***.***>
Sent: Friday, July 1, 2022 4:28:40 AM
To: PacktPublishing/Incident-Response-with-Threat-Intelligence ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PacktPublishing/Incident-Response-with-Threat-Intelligence] Trying to find Corp-Laptop VM (Issue #1)


Virtual machines folder shows no corp-laptop VM files

**Comment by CyberMakanju** [comment]
I cannot install the VM snapshot. saying I need the vmx configuration file. please help.
